/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    AstralEnvironment: typeof import('./src/components/astral/AstralEnvironment.vue')['default']
    AstralModeControl: typeof import('./src/components/astral/AstralModeControl.vue')['default']
    AuthLayout: typeof import('./src/components/auth/AuthLayout.vue')['default']
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    BaseIconButton: typeof import('./src/components/ui/BaseIconButton.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyState: typeof import('./src/components/states/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/states/ErrorState.vue')['default']
    GalleryGrid: typeof import('./src/components/gallery/GalleryGrid.vue')['default']
    GalleryItem: typeof import('./src/components/gallery/GalleryItem.vue')['default']
    HomeBatchQueue: typeof import('./src/components/home/HomeBatchQueue.vue')['default']
    HomeToolbar: typeof import('./src/components/home/HomeToolbar.vue')['default']
    ImageCard: typeof import('./src/components/ImageCard.vue')['default']
    ImageCommentsSection: typeof import('./src/components/detail/ImageCommentsSection.vue')['default']
    ImageDetailInfoPanel: typeof import('./src/components/detail/ImageDetailInfoPanel.vue')['default']
    ImageMetadata: typeof import('./src/components/gallery/ImageMetadata.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    ImageViewer: typeof import('./src/components/ImageViewer.vue')['default']
    LoadingState: typeof import('./src/components/states/LoadingState.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NotificationBell: typeof import('./src/components/NotificationBell.vue')['default']
    NotificationDrawer: typeof import('./src/components/NotificationDrawer.vue')['default']
    ProfileAvatarEditor: typeof import('./src/components/profile/ProfileAvatarEditor.vue')['default']
    ProfileBackgroundEditor: typeof import('./src/components/profile/ProfileBackgroundEditor.vue')['default']
    ProfileHeader: typeof import('./src/components/profile/ProfileHeader.vue')['default']
    ProfileWorksSection: typeof import('./src/components/profile/ProfileWorksSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SquareDiscoveryAside: typeof import('./src/components/square/SquareDiscoveryAside.vue')['default']
    SquareHeroFilters: typeof import('./src/components/square/SquareHeroFilters.vue')['default']
    SquareImageDrawer: typeof import('./src/components/square/SquareImageDrawer.vue')['default']
    TagInput: typeof import('./src/components/TagInput.vue')['default']
    TurnstileWidget: typeof import('./src/components/TurnstileWidget.vue')['default']
    UserIdentity: typeof import('./src/components/ui/UserIdentity.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
