<template><Transition name="batch-queue"><footer v-if="visible" class="batch-queue"><span>已选图片</span><div class="queue-strip"><button v-for="img in images" :key="img.uuid" class="queue-thumb" type="button" :title="imageAlt(img)" @click="emit('toggle',img.uuid)"><img v-if="displayUrl(img)" :src="displayUrl(img)" :alt="imageAlt(img)" loading="lazy" decoding="async" /></button></div><div class="queue-actions"><button class="secondary-command" type="button" :disabled="selectedCount===0" @click="emit('clear')">清空</button><button class="primary-command" type="button" :disabled="selectedCount===0" @click="emit('delete')">删除</button></div></footer></Transition></template>
<script setup>
import { getImageAlt } from '../../utils/imageRequests'
defineProps({visible:{type:Boolean,default:false},images:{type:Array,default:()=>[]},selectedCount:{type:Number,default:0},displayUrl:{type:Function,required:true}})
const emit=defineEmits(['toggle','clear','delete'])
const imageAlt = getImageAlt
</script>
<style scoped>
.batch-queue{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:var(--space-4);padding:var(--space-3) var(--space-4);border:1px solid var(--color-border-subtle);background:var(--color-canvas-muted)}.batch-queue>span{color:var(--color-text-secondary);font-size:var(--text-sm)}.queue-strip{display:flex;gap:var(--space-2);overflow:auto}.queue-thumb{width:48px;height:48px;flex:0 0 auto;padding:0;overflow:hidden;border:1px solid var(--color-border-subtle);border-radius:var(--radius-xs);background:var(--color-surface-2);cursor:pointer}.queue-thumb img{width:100%;height:100%;object-fit:cover}.queue-actions{display:flex;gap:var(--space-2)}button{min-height:var(--control-height-md);padding:0 var(--space-3);border:1px solid var(--color-border-subtle);border-radius:var(--radius-sm);background:var(--color-surface-1);color:var(--color-text-primary);cursor:pointer}.primary-command{border-color:var(--color-error);color:var(--color-error)}button:disabled{opacity:.45;cursor:not-allowed}@media(max-width:650px){.batch-queue{grid-template-columns:1fr}.queue-actions button{min-height:var(--control-height-lg);flex:1}}
.batch-queue-enter-active,.batch-queue-leave-active{transition:opacity var(--duration-standard) var(--ease-out),transform var(--duration-standard) var(--ease-out)}
.batch-queue-enter-from,.batch-queue-leave-to{opacity:0;transform:translateY(12px)}
@media(prefers-reduced-motion:reduce){.batch-queue-enter-active,.batch-queue-leave-active{transition:opacity 200ms ease}.batch-queue-enter-from,.batch-queue-leave-to{opacity:0;transform:none}}
</style>
