import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const authLayout = readFileSync('src/components/auth/AuthLayout.vue', 'utf8')
const login = readFileSync('src/views/Login.vue', 'utf8')
const register = readFileSync('src/views/Register.vue', 'utf8')

describe('authentication page stage two contract', () => {
  it('keeps AuthLayout presentation-only and freezes the Astral matte two-column structure', () => {
    expect(authLayout).toContain("default: 'narrow'")
    expect(authLayout).toContain("['narrow', 'wide']")
    expect(authLayout).toContain('<slot name="aside" />')
    expect(authLayout).toContain('<slot name="header" />')
    expect(authLayout).toContain('<slot name="footer" />')
    expect(authLayout).toMatch(/width: min\(100%, 1120px\)/)
    expect(authLayout).toMatch(/grid-template-columns: minmax\(280px, 0\.85fr\) minmax\(420px, 1\.15fr\)/)
    expect(authLayout).not.toMatch(/from ['"].*router|from ['"].*api|from ['"].*pinia|useRouter|useUserStore/)
    expect(authLayout).not.toMatch(/linear-gradient|radial-gradient/)
    expect([...authLayout.matchAll(/box-shadow:\s*([^;]+)/g)].map(match => match[1].trim())).toEqual(['var(--shadow-dialog)', 'none', 'none'])
    expect(authLayout).not.toContain('.auth-brand')
    expect(authLayout).toContain('font-size: clamp(48px, 4.6vw, 64px)')
    expect(authLayout).toMatch(/\.auth-aside :deep\(\.auth-aside-eyebrow\)[\s\S]*border-left: 2px solid var\(--color-vermilion\)/)
  })

  it('keeps Login focused on login flows and preserves every real entry point', () => {
    expect(login).toContain('form-width="narrow"')
    expect(login).toContain('loginMode')
    expect(login).toContain('loginByCode')
    expect(login).toContain('sendCode')
    expect(login).toContain('getGithubAuthUrl')
    expect(login).toContain('getGoogleAuthUrl')
    expect(login).toContain('TurnstileWidget')
    expect(login).toContain('to="/register"')
    expect(login).toContain('autocomplete="username"')
    expect(login).toContain('autocomplete="current-password"')
    expect(login).toContain('autocomplete="one-time-code"')
    expect(login).toContain('role="tab"')
    expect(login).toContain(':aria-selected="loginMode')
    expect(login).not.toContain('class="auth-brand"')
    expect(login).not.toContain('私人图库')
    expect(login).not.toMatch(/registerForm|registerLoading|registerRules|registerCaptcha|registerCountdown|handleRegister|loadRegisterCaptcha/)
    expect(login).not.toMatch(/linear-gradient|radial-gradient|background:\s*#0|background:\s*rgba\(/)
    expect(login).toContain('继续整理、分享')
    expect(login).toContain('留住喜欢的画面，也留住再次回看的理由')
    expect(login).not.toContain('留住喜欢的画面，也留住再次回看的理由。')
    expect(login).toContain('回到已经留下的内容')
    expect(login).not.toContain('回到已经留下的内容。')
    expect(login).toContain('分享愿意公开的内容')
    expect(login).toContain('class="login-form-stage"')
    expect(login).not.toContain('min-height: 510px')
  })

  it('renders the OAuth providers as screenshot-aligned vertical brand buttons', () => {
    const googleLabel = login.indexOf('使用 Google 继续')
    const githubLabel = login.indexOf('使用 GitHub 继续')
    const microsoftLabel = login.indexOf('使用 Microsoft 继续')

    expect(googleLabel).toBeGreaterThan(-1)
    expect(githubLabel).toBeGreaterThan(googleLabel)
    expect(microsoftLabel).toBeGreaterThan(githubLabel)
    expect(login).toContain("../assets/brands/google.svg")
    expect(login).toContain("../assets/brands/github.svg")
    expect(login).toContain("../assets/brands/microsoft.svg")
    expect(login).not.toContain('<svg class="oauth-icon"')
    expect(login).toMatch(/\.oauth-row\s*\{[\s\S]*grid-template-columns:\s*1fr/)
    expect(login).toMatch(/\.oauth-btn\s*\{[\s\S]*width:\s*100%[\s\S]*min-height:\s*62px/)
    expect(login).toMatch(/\.oauth-icon\s*\{[\s\S]*width:\s*24px[\s\S]*height:\s*24px/)
  })

  it('keeps Register as the single registration implementation with ordered safeguards', () => {
    expect(register).toContain('form-width="wide"')
    expect(register).toContain('register({ ...payload, turnstileToken: token })')
    expect(register).toContain('sendCode({')
    expect(register).toContain('TurnstileWidget')
    expect(register).not.toContain('agreedToTerms')
    expect(register).not.toContain('服务条款')
    expect(register).not.toContain('隐私说明')
    expect(register).toContain('native-type="submit"')
    expect(register).toContain('autocomplete="new-password"')
    expect(register).toContain('autocomplete="email"')
    expect(register).toContain('autocomplete="one-time-code"')
    expect(register).not.toContain('class="auth-brand"')
    expect(register).not.toMatch(/linear-gradient|radial-gradient|background:\s*#0|background:\s*rgba\(/)
    expect(register).toContain('开始创建、上传')
    expect(register).toContain('把零散的图片，慢慢整理成自己的收藏')
    expect(register).not.toContain('把零散的图片，慢慢整理成自己的收藏。')
    expect(register).toContain('<h1 class="auth-title">创建账号</h1>')
    expect(register).toContain("validateFields(['email'])")
    expect(register).toContain('prepareRegisterPayload(form)')
    expect(register).toContain('email-code-feedback')
    expect(register).toContain('register-feedback')
    expect(register).toContain('type="primary"')
  })

  it('checks graphical captcha only when a user submits registration or login', () => {
    expect(register).toContain('prepareRegisterPayload(form)')
    expect(register).toContain("captchaId: ''")
    expect(register).toContain("captchaCode: ''")
    expect(login).toContain("const form = reactive({ username: '', password: '', captchaId: '', captchaCode: '' })")
    expect(login).toContain('login({ ...form, turnstileToken: token })')
    expect(login).toContain('loginByCode({ ...emailForm, turnstileToken: token })')
  })

  it('keeps validation feedback and the account footer from shifting the auth panel', () => {
    expect(authLayout).toMatch(/\.auth-body :deep\(\.auth-form \.el-form-item__error\)\s*\{[\s\S]*position:\s*absolute/)
    expect(authLayout).toMatch(/\.auth-footer\s*\{[\s\S]*margin-top:/)
    expect(authLayout).toMatch(/\.auth-page\s*\{[\s\S]*height:\s*100dvh;[\s\S]*overflow:\s*hidden;/)
    expect(authLayout).toMatch(/\.auth-layout\s*\{[\s\S]*height:\s*min\(880px, calc\(100dvh - 64px\)\);/)
    expect(authLayout).toMatch(/grid-template-rows:\s*minmax\(0, 1fr\)/)
    expect(authLayout).toMatch(/\.auth-main\s*\{[\s\S]*overflow-y:\s*auto;[\s\S]*scrollbar-gutter:\s*stable;/)
    expect(authLayout).toMatch(/scrollbar-color:\s*var\(--color-text-secondary\) var\(--color-canvas-muted\)/)
    expect(authLayout).toMatch(/scrollbar-width:\s*auto/)
    expect(authLayout).toMatch(/\.auth-main::\-webkit-scrollbar\s*\{[\s\S]*width:\s*12px/)
    expect(authLayout).toMatch(/justify-content:\s*flex-start/)
    expect(authLayout).toMatch(/\.auth-main__inner::after\s*\{[\s\S]*flex:\s*0 0 32px/)
    expect(authLayout).toMatch(/\.auth-body :deep\(\.submit-row\)\s*\{[\s\S]*margin-bottom:\s*0 !important/)
    expect(authLayout).toMatch(/@media \(max-width: 900px\)[\s\S]*\.auth-page\s*\{[\s\S]*height:\s*auto;[\s\S]*overflow:\s*visible;/)
  })
})
