import type { Preset, PresetName } from '@/types/particle';

export const presets: Record<PresetName, Preset> = {
  fireworks: {
    name: 'fireworks',
    label: '烟花',
    icon: '🎆',
    explosion: {
      particleCount: 80,
      speed: 300,
      gravity: 200,
      size: 4,
      sizeVariance: 2,
      colors: ['#ff6b6b', '#ffd93d', '#6bcb77', '#4d96ff', '#ff922b', '#f06595'],
      rings: 2,
    },
    trail: {
      density: 0.5,
      size: 2.5,
      decay: 0.4,
      color: '#ffd93d',
    },
  },
  neon: {
    name: 'neon',
    label: '霓虹',
    icon: '💜',
    explosion: {
      particleCount: 50,
      speed: 150,
      gravity: 50,
      size: 5,
      sizeVariance: 3,
      colors: ['#ff00ff', '#00ffff', '#ff0080', '#00ff88', '#8800ff', '#00d4ff'],
      rings: 1,
    },
    trail: {
      density: 0.8,
      size: 3.5,
      decay: 0.6,
      color: '#00ffff',
    },
  },
  stars: {
    name: 'stars',
    label: '星空',
    icon: '🌟',
    explosion: {
      particleCount: 40,
      speed: 100,
      gravity: 0,
      size: 2,
      sizeVariance: 1,
      colors: ['#ffffff', '#ffe9c4', '#d4f0ff', '#fff8e7', '#e8e8ff'],
      rings: 1,
    },
    trail: {
      density: 0.3,
      size: 1.5,
      decay: 0.3,
      color: '#ffffff',
    },
  },
  firefly: {
    name: 'firefly',
    label: '萤火虫',
    icon: '🪲',
    explosion: {
      particleCount: 30,
      speed: 80,
      gravity: -10,
      size: 6,
      sizeVariance: 4,
      colors: ['#ffdd57', '#ffc107', '#ffe082', '#fff176', '#ffcc02'],
      rings: 1,
    },
    trail: {
      density: 0.4,
      size: 4,
      decay: 0.8,
      color: '#ffdd57',
    },
  },
  confetti: {
    name: 'confetti',
    label: '碎纸',
    icon: '🎊',
    explosion: {
      particleCount: 100,
      speed: 350,
      gravity: 150,
      size: 3,
      sizeVariance: 2,
      colors: ['#ff6b6b', '#ffd93d', '#6bcb77', '#4d96ff', '#ff922b', '#ff0080', '#00ff88', '#845ef7'],
      rings: 1,
    },
    trail: {
      density: 0.6,
      size: 2,
      decay: 0.5,
      color: '#ff6b6b',
    },
  },
};
