<template><section class="user-works"><div class="works-heading"><div><span class="section-label">PUBLIC WORKS</span><h2>创作作品</h2></div><div v-if="owner&&items.length" class="works-actions"><el-checkbox :model-value="allSelected" :indeterminate="partiallySelected" @change="emit('toggle-all',$event)">全选本页</el-checkbox><el-button v-if="selectedUuids.length" @click="emit('clear')">取消选择</el-button><el-button v-if="selectedUuids.length" type="danger" @click="emit('batch-delete')">删除选中 {{ selectedUuids.length }}</el-button></div></div><GalleryGrid :items="items" :loading="loading" :error="error" :initial-eager-count="4" empty-title="还没有分享过创作" empty-description="" error-description="作品列表请求失败，请检查连接后重试。" @retry="emit('retry')"><template #item="{item,priority}"><ImageCard :image="item" :priority="priority" :show-actions="owner" :selectable="owner" :selected="selectedUuids.includes(item.uuid)" @delete="emit('delete',$event)" @edit="emit('edit',$event)" @copy="emit('copy',$event)" @toggle-select="emit('toggle',$event)" /></template></GalleryGrid></section></template>
<script setup>
import GalleryGrid from '../gallery/GalleryGrid.vue'
import ImageCard from '../ImageCard.vue'
defineProps({items:{type:Array,default:()=>[]},loading:{type:Boolean,default:false},error:{type:Boolean,default:false},owner:{type:Boolean,default:false},selectedUuids:{type:Array,default:()=>[]},allSelected:{type:Boolean,default:false},partiallySelected:{type:Boolean,default:false}})
const emit=defineEmits(['toggle-all','clear','batch-delete','retry','delete','edit','copy','toggle'])
</script>
<style scoped>
.user-works{padding:var(--space-6);border:1px solid var(--color-border-subtle);background:var(--color-surface-1)}.works-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:var(--space-4);margin-bottom:var(--space-5)}.section-label{color:var(--color-vermilion);font-size:var(--text-xs);font-weight:700;letter-spacing:.08em}.works-heading .section-label{display:inline-block;padding-left:var(--space-3);border-left:2px solid var(--color-vermilion)}h2{margin:var(--space-1) 0 0;font-family:var(--font-title);font-size:var(--text-3xl);font-weight:600}.works-actions{display:flex;align-items:center;flex-wrap:wrap;gap:var(--space-2)}@media(max-width:650px){.user-works{padding:var(--space-4)}.works-heading{align-items:flex-start;flex-direction:column}.works-actions :deep(.el-button){min-height:44px}}
</style>
