import type { Preset, PresetName } from './types';

export const presets: Record<PresetName, Preset> = {
  fireworks: {
    name: 'fireworks',
    label: '烟花',
    icon: '🎆',
    explosion: {
      particleCount: 80,
      speed: 300,
      gravity: 200,
      size: 4,
      sizeVariance: 2,
      colors: ['#ff6b6b', '#ffd93d', '#6bcb77', '#4d96ff', '#ff922b', '#f06595'],
      rings: 2,
    },
    trail: {
      density: 0.5,
      size: 2.5,
      decay: 0.4,
      color: '#1a1a1a',
    },
  },
  neon: {
    name: 'neon',
    label: '霓虹',
    icon: '💜',
    explosion: {
      particleCount: 50,
      speed: 150,
      gravity: 50,
      size: 5,
      sizeVariance: 3,
      colors: ['#c026d3', '#0891b2', '#db2777', '#059669', '#7c3aed', '#0284c7'],
      rings: 1,
    },
    trail: {
      density: 0.8,
      size: 3.5,
      decay: 0.6,
      color: '#7c3aed',
    },
  },
  stars: {
    name: 'stars',
    label: '星空',
    icon: '🌟',
    explosion: {
      particleCount: 40,
      speed: 100,
      gravity: 0,
      size: 2,
      sizeVariance: 1,
      colors: ['#1e3a5f', '#3d3d3d', '#2d1b69', '#1a1a1a', '#5c3d2e'],
      rings: 1,
    },
    trail: {
      density: 0.3,
      size: 1.5,
      decay: 0.3,
      color: '#3d3d3d',
    },
  },
  firefly: {
    name: 'firefly',
    label: '萤火虫',
    icon: '🪲',
    explosion: {
      particleCount: 30,
      speed: 80,
      gravity: -10,
      size: 6,
      sizeVariance: 4,
      colors: ['#e6a817', '#c7523a', '#d97706', '#b45309', '#92400e'],
      rings: 1,
    },
    trail: {
      density: 0.4,
      size: 4,
      decay: 0.8,
      color: '#e6a817',
    },
  },
  confetti: {
    name: 'confetti',
    label: '碎纸',
    icon: '🎊',
    explosion: {
      particleCount: 100,
      speed: 350,
      gravity: 150,
      size: 3,
      sizeVariance: 2,
      colors: ['#ff6b6b', '#ffd93d', '#6bcb77', '#4d96ff', '#ff922b', '#ff0080', '#00ff88', '#845ef7'],
      rings: 1,
    },
    trail: {
      density: 0.6,
      size: 2,
      decay: 0.5,
      color: '#1a1a1a',
    },
  },
};
